# Generated by Django 5.2.1 on 2025-07-30 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=20)),
                ('DoctorDepartement', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('AaadharNo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mob', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
