# Generated by Django 5.2.1 on 2025-07-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
