# Generated by Django 5.2.1 on 2025-08-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_doctor_doctorname_alter_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('Appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.appointment')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
